extends Control

var MAIN_MENU_MUSIC = "res://music/menu_principal.ogg"

func _ready():
	BackgroundMusic.crossfade_to(MAIN_MENU_MUSIC, -10, 1)


func load_main_game():
	get_tree().change_scene("res://scenes/Main.tscn")


func load_credits():
	get_tree().change_scene("res://scenes/Credits.tscn")


func _on_NewGameButton_pressed():
	Dialogic.reset_saves()
	load_main_game()


func _on_ContinueButton_pressed():
	load_main_game()


func _on_ExitButton_pressed():
	get_tree().quit(0)


func _on_CreditsButton_pressed():
	load_credits()

